# Generated by Django 5.2 on 2025-05-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeupload',
            name='uploaded_at',
        ),
    ]
